services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - db:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
  next:
    build: .
    ports:
      - 3000:3000
      - 5555:5555
    links:
      - db
    environment:
      - POSTGRES_PRISMA_URL = postgresql://postgres:admin@db:5432/postgres?schema=public
    develop:
      watch:
        - action: sync
          path: .
          target: /usr/src/app
          ignore:
            - node_modules/
            - package.json
            - prisma/schema.prisma
        - action: rebuild
          path: package.json
        - action: rebuild
          path: prisma/schema.prisma
    env_file:
      - .docker.env
volumes:
  db:
    driver: local
