services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - db:/var/lib/postgresql/data
    expose:
      - 5432
  next:
    build: .
    ports:
      - 3000:3000
    links:
      - db
    develop:
      watch:
        - action: sync
          path: .
          target: .
          ignore:
            - node_modules/
            - package.json
        - action: rebuild
          path: package.json
    env_file:
      - .env
volumes:
  db:
    driver: local
